name: Compile sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches/README.md
      - name: Compile sketch
        # TODO: change to @v1 after the release
        uses: arduino/compile-sketches@main
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to configure the action with multiple sketch paths if needed.
            - ./
          libraries: |
            # The "blink" sketch being compiled in this demo doesn't use any libraries, so just define an empty list
            -
